
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gateway?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: abc123

zuul:
  routes:
    products:
      path: /products/**
      serviceId: product
      stripPrefix: true
      retryable: true
#
#mall:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.example.gateway.PriorityServiceList
#
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100
##    retryable
#
#    retryableStatusCodes: 404, 502, 500
#    MaxAutoRetries: 1
#    MaxAutoRetriesNextServer: 10
#    OkToRetryOnAllOperations: true
#    ConnectTimeout: 1000
#    ReadTimeout: 3000


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9876/eureka