
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gateway?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: abc123

zuul:
  routes:
    products:
      path: /products/**
      serviceId: productService
      stripPrefix: false
      retryable: true

productService:
  ribbon:
    NFLoadBalancerRuleClassName: com.example.gateway.PriorityServiceList

    listOfServers: http://localhost:8081


    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
#    retryable

    retryableStatusCodes: 404, 502, 500
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 10
    OkToRetryOnAllOperations: true
    ConnectTimeout: 1000
    ReadTimeout: 3000